/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function getUsers() {
    return invoke()<User[]>("get_users")
}

export function newUser(email: string) {
    return invoke()<User>("new_user", { email })
}

export type User = { id: number; email: string; name: string | null }
