/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function greet(name: string) {
    return invoke()<string>("greet", { name })
}

export function systemSound(sound: MacOSSystemSound, speed: number, volume: number, time: number) {
    return invoke()<null>("system_sound", { sound,speed,volume,time })
}

export function voiceSay(message: string) {
    return invoke()<null>("voice_say", { message })
}

export function startCompanionMode() {
    return invoke()<null>("start_companion_mode")
}

export type MacOSSystemSound = "Basso" | "Blow" | "Bottle" | "Frog" | "Funk" | "Glass" | "Hero" | "Morse" | "Ping" | "Pop" | "Purr" | "Sosumi" | "Submarine" | "Tink"
